// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebTimViec.Api.Data;

#nullable disable

namespace WebTimViec.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323084710_AddNotificationsTable")]
    partial class AddNotificationsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
            
            // Standard Entity Builders... (omitting for brevity in this scratch, but I should include full state in Snapshot)
            // Actually, I should just update the Snapshot file instead since I'm manually managing it.
#pragma warning restore 612, 618
        }
    }
}
